// packages/react/src/components/Overlay.tsx
import React, { ReactElement, ReactNode } from "react";
import { DjangoBridgeResponse, Frame, Message } from "@common";
import Config from "../config";
import {
  MessagesContext,
  OverlayContext,
  OverlayContextType,
} from "../contexts";
import { DirtyFormContext } from "../dirtyform";
import { NavigationController, useNavigationController } from "../navigation";
import Browser from "./Browser";

export interface OverlayProps {
  config: Config;
  initialResponse: DjangoBridgeResponse;
  initialPath: string;
  parentNavigationController: NavigationController;
  render: (content: ReactNode) => ReactNode;
  requestClose: () => void;
  closeRequested: boolean;
  onCloseCompleted: () => void;
  onServerError: (kind: "server" | "network") => void;
}

export default function Overlay({
  config,
  initialResponse,
  initialPath,
  parentNavigationController,
  render,
  requestClose,
  closeRequested,
  onCloseCompleted,
  onServerError,
}: OverlayProps): ReactElement {
  const { pushMessage } = React.useContext(MessagesContext);

  const navigationController = useNavigationController(
    parentNavigationController,
    config.unpack,
    initialResponse,
    initialPath,
    {
      onNavigation: (
        frame: Frame | null,
        newFrame: boolean,
        messages: Message[]
      ) => {
        // Push any new messages from server
        messages.forEach(pushMessage);
      },
      onEscalate: () => {
        onCloseCompleted();
      },
      onOverlayClose: (messages: Message[]) => {
        // Push any new messages from server
        messages.forEach(pushMessage);

        // Request close
        requestClose();
      },
      onServerError,
    }
  );

  // If close is requested, but there is a dirty form (form without saved changes) in the overlay, block the close
  const dirtyFormContext = React.useContext(DirtyFormContext);
  const requestCloseCallback = React.useCallback(
    ({ skipDirtyFormCheck = false }: { skipDirtyFormCheck?: boolean } = {}) => {
      if (!skipDirtyFormCheck && dirtyFormContext.isDirty) {
        // eslint-disable-next-line no-void
        void dirtyFormContext.requestUnload().then(() => requestClose());
      } else {
        requestClose();
      }
    },
    [dirtyFormContext, requestClose]
  );

  const overlayContext: OverlayContextType = React.useMemo(
    () => ({
      overlay: true,
      closeRequested,
      requestClose: requestCloseCallback,
      onCloseCompleted,
    }),
    [closeRequested, onCloseCompleted, requestCloseCallback]
  );

  if (navigationController.isLoading) {
    // eslint-disable-next-line react/jsx-no-useless-fragment
    return <></>;
  }

  return (
    <OverlayContext.Provider value={overlayContext}>
      {render(
        <Browser
          config={config}
          navigationController={navigationController}
          openOverlay={() => {}}
        />
      )}
    </OverlayContext.Provider>
  );
}

// packages/vue/src/components/Overlay.vue
<template>
  <div v-if="!navigationController.isLoading">
    <slot :content="browserContent" />
  </div>
</template>

<script setup lang="ts">
import { computed, provide, inject, h } from 'vue';
import { DjangoBridgeResponse, Frame, Message } from '../common';
import Config from '../config';
import { MessagesKey, OverlayKey, OverlayContextType } from '../contexts';
import { DirtyFormKey } from '../dirtyform';
import { NavigationController, useNavigationController } from '../navigation';
import Browser from './Browser.vue';

interface Props {
  config: Config;
  initialResponse: DjangoBridgeResponse;
  initialPath: string;
  parentNavigationController: NavigationController;
  render: (content: any) => any;
  requestClose: () => void;
  closeRequested: boolean;
  onCloseCompleted: () => void;
  onServerError: (kind: "server" | "network") => void;
}

const props = defineProps<Props>();

const messages = inject(MessagesKey);
if (!messages) {
  throw new Error("Overlay must be used within a MessagesProvider");
}

const { pushMessage } = messages;

const navigationController = useNavigationController(
  props.parentNavigationController,
  props.config.unpack,
  props.initialResponse,
  props.initialPath,
  {
    onNavigation: (
      frame: Frame | null,
      newFrame: boolean,
      messages: Message[]
    ) => {
      // Push any new messages from server
      messages.forEach(pushMessage);
    },
    onEscalate: () => {
      props.onCloseCompleted();
    },
    onOverlayClose: (messages: Message[]) => {
      // Push any new messages from server
      messages.forEach(pushMessage);

      // Request close
      props.requestClose();
    },
    onServerError: props.onServerError,
  }
);

// If close is requested, but there is a dirty form (form without saved changes) in the overlay, block the close
const dirtyForm = inject(DirtyFormKey);
if (!dirtyForm) {
  throw new Error("Overlay must be used within a DirtyFormScope");
}

const requestCloseCallback = (
  { skipDirtyFormCheck = false }: { skipDirtyFormCheck?: boolean } = {}
) => {
  if (!skipDirtyFormCheck && dirtyForm.isDirty) {
    dirtyForm.requestUnload().then(() => props.requestClose());
  } else {
    props.requestClose();
  }
};

const overlayContext: OverlayContextType = computed(() => ({
  overlay: true,
  closeRequested: props.closeRequested,
  requestClose: requestCloseCallback,
  onCloseCompleted: props.onCloseCompleted,
}));

provide(OverlayKey, overlayContext.value);

const browserContent = computed(() => {
  return h(Browser, {
    config: props.config,
    navigationController,
    openOverlay: () => {}, // Nested overlays not supported
  });
});
</script>
